spring.application.name=energiai

spring.datasource.url=jdbc:postgresql://localhost:5432/energi_ai
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=usuario_bd
spring.datasource.password=password_bd

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
